spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rposi?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #hibernate:
      #ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  security:
    jwt:
      secret-key: sync-app-security-key-for-newer-security-spring-boot-3-app
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  servlet:
    contextPath: /syn-app-api
  port: 9091
  use-forward-headers: true
  tomcat:
    protocol-header: X-Forwarded-App-Proto
    port-header: X-Forwarded-App-Port
    
logging:
  path: H:/Raz/temp/syc-app-log
  #path: /opt/sync-app-log
  level:
    org:
      springframework:
      web: DEBUG
